// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WarnAboutTODOs
{
    internal sealed partial class Vsix
    {
        public const string Id = "WarnAboutTODOs.c50458a5-b99a-484f-be10-f1a8714c1453";
        public const string Name = "Warn About TODOs";
        public const string Description = @"Displays warnings for TODO notes in comments";
        public const string Language = "en-US";
        public const string Version = "1.7.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
